### ISSUE TITLE
Error in operations.getFolderContent: 401 - undefined

### ISSUE THREAD

**Issue by raghuureddy** [s-KaiNet/node-sp-auth#6] opened 2017-01-12 05:17 UTC
Hello,

I'm facing 401 error with SharePoint On-prem NTLM. Passing current user/password but on server event logs i see audit failure for the first time & then succeeded using Kerberos.

But its failing in node js & below is the msg..
Error in operations.getFolderContent: 401 - undefined (sppull)

**Comment by koltyakov** [comment] 2017-01-12 07:08
Hi @raghuureddy,

Could you share your config file? On-prem config should contain username, password and **domain** parameters. I guess that you have `domain` parameter missed.

**Comment by koltyakov** [comment] 2017-01-12 14:08
This issue is redundant here. Duplicate of https://github.com/koltyakov/sppull/issues/13, where the discussion is taken place.
It's more likely an environment issue but not the node-sp-auth or sppull.
So I suggest to close it here.

**Comment by s-KaiNet** [comment] 2017-01-12 20:13
Ok, thanks Andrew
I've subscribed to corresponding issue inside `sppull` to see how it's going.

**Closed by s-KaiNet** 2017-01-12 20:13 UTC
